### ISSUE TITLE
no entities showing

### ISSUE THREAD

**Issue by craggus2000** [midstar/homeassistant_tuya_with_bht-002_support#1]
Hi,
I've just tried using your workaround, and am getting the following error after configuring the custom_component integration : Unable to prepare setup for platform tuya.climate: Platform not found (cannot import name 'SWING_BOTH' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).

This happens after adding the BHT-002 device. It addes the device but no entities are visible.

I'm running latest HA 2022.9.7. 

Can you please advise?
Many thanks

**Comment by ickard77** [comment]
Can confirm, get exactly the same behavior and problems with the installation unfortunately.

Many thanks

**Comment by craggus2000** [comment]
Would still appreciate advice from @midstar , however I think I may have solve this.....

The climate.py file - I DIDN'T apply the changes in the section

> from homeassistant.components.climate import (
>     SWING_BOTH,
>     SWING_HORIZONTAL,
>     SWING_OFF,
>     SWING_ON,
>     SWING_VERTICAL,
>     ClimateEntity,
>     ClimateEntityDescription,
>     ClimateEntityFeature,
>     HVACMode,
> )

so kept it as

> from homeassistant.components.climate import ClimateEntity, ClimateEntityDescription
> from homeassistant.components.climate.const import (
>     SWING_BOTH,
>     SWING_HORIZONTAL,
>     SWING_OFF,
>     SWING_ON,
>     SWING_VERTICAL,
>     ClimateEntityFeature,
>     HVACMode,
> )

The files changed from main release were the base.py and climate.py. So I replaced the base.py with the file supplied by midstar and just did a diff between his climate.py and the original climate.py and made the change at the bottom of the file.


@midstar, I don't understand why this _appears_ to have made it work, so would really appreciate your insight please!
But many thanks for your overall solution!

**Comment by ickard77** [comment]
Thanks @craggus2000, i tried it too and it seems to work fine.

Following the thread.

Thank you Mr. @midstar  for your overall solution!

**Comment by midstar** [comment]
Hi,

I have merged the tuya_BHT-002_thermostat_workaround branch a couple of time with the master branch. However, the master branch seems to have non-compatible changes in the Home Assistant API with the official released Home Assistant version. To be honest I did never try the component with these changes and thus did not see this error.

I resetted the branch to the first commit which I'm currently using myself. 

**Please try the instruction again. It should work now.**

However, in later Home Assistant versions I will probably need to update tuya_BHT-002_thermostat_workaround again. 

Since I'm using the custom component and regulary updating the Home Assistant version I will detect incompatible changes and update the tuya_BHT-002_thermostat_workaround branch.

**Comment by midstar** [comment]
I digged into this a little more. Home assistant 2022.10.x will introduce the backwards incompatible changes you identified above. 

Once this version is released I will update tuya_BHT-002_thermostat_workaround branch
